name: Deploy WebApp

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/webapp/**'
      - 'packages/core/**'
      - '.github/workflows/deploy-webapp.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  PNPM_VERSION: 8.15.0

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment:
      name: staging
      url: https://staging.nuvexsell.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter @nuvexsell/core build
          pnpm --filter @nuvexsell/scraper build
          pnpm --filter @nuvexsell/ai-scoring build
          pnpm --filter @nuvexsell/ops-automation build

      - name: Build webapp
        run: pnpm --filter @nuvexsell/webapp build
        env:
          NEXT_PUBLIC_API_URL: https://nuvexsell-worker-staging.your-domain.workers.dev

      - name: Deploy to Cloudflare Pages (Staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/webapp/out --project-name=nuvexsell-staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment:
      name: production
      url: https://app.nuvexsell.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter @nuvexsell/core build
          pnpm --filter @nuvexsell/scraper build
          pnpm --filter @nuvexsell/ai-scoring build
          pnpm --filter @nuvexsell/ops-automation build

      - name: Build webapp
        run: pnpm --filter @nuvexsell/webapp build
        env:
          NEXT_PUBLIC_API_URL: https://api.nuvexsell.com

      - name: Deploy to Cloudflare Pages (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/webapp/out --project-name=nuvexsell-production